#!/usr/bin/bash

cd "$(dirname "$0")"

case "$1" in
    "")
        cat ./active-mode
        exit
        ;;
    "lock")
        touch lock
        exit
        ;;
    "unlock")
        rm -f lock
        exit
        ;;
    "locked")
        if ls lock &>/dev/null; then
            exit
        fi
        exit 1
        ;;
    "toggle")
        if [[ "$2" = "lock" ]]; then
            if ./mode locked; then
                ./mode unlock
            else
                ./mode lock
            fi
            exit
        fi
        ;;
esac

if ./mode locked; then
    if [[ "$1" = "force" ]]; then
        shift 1
        FORCE="force"
    else
        if [[ $(./mode) = "$1" ]]; then
            ./mode unlock
            exit
        fi
        echo "Locked"
        exit 1
    fi
fi

case "$1" in
    "laptop")
        killall -s SIGTERM screenrotator &
        eval "~/.config/polybar/mode $FORCE laptop &"
        echo laptop > ./active-mode
        ;;
    "tablet")
        eval "~/.config/polybar/mode $FORCE tablet &"
        eval "~/.config/polybar/mode $FORCE landscape &"
        screenrotator &
        echo tablet > ./active-mode
        ;;
    "toggle")
        if [[ "$(./mode)" = "laptop" ]]; then
            eval "./mode $FORCE tablet"
        else
            eval "./mode $FORCE laptop"
        fi
        ;;
    *)
        echo "Usage: $0 [[force] laptop|tablet|toggle | lock|unlock|locked|toggle lock]"
        ;;
esac
