#!/usr/bin/bash

cd "$(dirname "$0")"

case "$1" in
    "")
        cat ./active-mode
        exit
        ;;
    "lock")
        touch lock
        exit
        ;;
    "unlock")
        rm -f lock
        exit
        ;;
    "locked")
        if ls lock &>/dev/null; then
            exit
        fi
        exit 1
        ;;
    "toggle-lock")
        if ./mode locked; then
            ./mode unlock
        else
            ./mode lock
        fi
        exit
        ;;
esac

if ./mode locked; then
    if [[ $(./mode) -eq "$1" ]]; then
        ./mode unlock
        exit
    fi
    exit 1
fi

case "$1" in
    "laptop")
        killall -s SIGTERM screenrotator &
        ~/.config/polybar/mode laptop &
        echo laptop > ./active-mode
        ;;
    "tablet")
        ~/.config/polybar/mode tablet &
        ~/.config/polybar/mode landscape &
        screenrotator &
        echo tablet > ./active-mode
        ;;
    *)
        echo "Usage: $0 [lock|unlock|locked|toggle-lock|laptop|tablet]"
        ;;
esac
