[colors]
deepblue = #4f22a3
purple = #a3107d
pink = #d33682
red = #dc322f
orange = #cb4b16
yellow = #b58900
green = #589900
sealine = #2aa198
lightblue = #268bd2

ws-light-red = #cb4b16
ws-dark-red = #77401007

ws-light-blue = #268bd2
ws-dark-blue = #77102065

ws-light-purple = #A44BA0
ws-dark-purple = #77201134

light = #eee8d5
dark = #66172100
gray = #586e75
dark-gray = #073642


[bar/base]
enable-ipc = true

bottom = false
radius = 12
height = 35
offset-y = 15

background = ${colors.dark}
foreground = ${colors.light}

line-size = 2
separator = "  "

wm-restack = i3
override-redirect = true

font-0 = Fantasque Sans Mono:Bold:size=12
font-1 = FantasqueSansMono Nerd Font Mono:Bold:size=24;3
font-2 = FantasqueSansMono Nerd Font Mono:Bold:size=20;3
font-3 = FantasqueSansMono Nerd Font Mono:Bold:size=17;2


[bar/workspaces]
inherit = bar/base

width = 424
offset-x = 20

modules-left = workspaces 

[bar/tray]
inherit = bar/base

width = 200
offset-x = 1700

modules-left = placeholder
tray-position = center

[bar/main]
inherit = bar/base
width = 950
offset-x = 597

modules-center = date tempscript memory filesystem cpu brightness battery layout sound

[bar/placeholder]
height = 45

modules-left = placeholder
background = #00000000

[module/placeholder]
type = custom/text
content = " "



;Date
[module/date]
type = internal/date

time = %H:%M
time-alt = %H:%M
date = %A, %B %d
date-alt = %A, %B %d

format-prefix = "  "
format-padding = 2
format-underline = ${colors.deepblue}
format-foreground = ${colors.deepblue}
interval = 20

label = %time%
label-foreground = ${colors.light}


;Workspaces
[module/workspaces]
type = internal/i3

pin-workspaces = true
strip-wsnumbers = true
index-sort = true

format = <label-state>

label-dimmed-underline = ${colors.background}

label-focused = %index%
label-focused-background = ${colors.ws-dark-blue}
label-focused-underline = ${colors.ws-light-blue}
label-focused-padding = 3

label-unfocused = %index%
label-unfocused-foreground = ${colors.gray}
label-unfocused-background = ${colors.dark}
label-unfocused-padding = 2

label-visible = %index%
label-visible-background = ${colors.ws-dark-purple}
label-visible-underline = ${colors.ws-light-purple}
label-visible-padding = 2

label-urgent = %index%
label-urgent-background = ${colors.ws-dark-red}
label-urgent-underline = ${colors.ws-light-red}
label-urgent-padding = 2



;Sound
[module/sound]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-volume-padding = 2
format-volume-underline = ${colors.lightblue}

label-volume = %percentage:2%%

label-muted =  %percentage:2%%
label-muted-padding = 2
label-muted-foreground = ${colors.gray}
label-muted-underline = ${colors.gray}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.lightblue}


;Brightness
[module/brightness]
type = internal/backlight
card = intel_backlight
format = <label>
format-padding = 2
format-prefix = " "
format-underline = ${colors.yellow}
format-prefix-foreground = ${colors.yellow}

label = %percentage:2%%


;Keyboard Layout
[module/layout]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = caps lock
blacklist-2 = scroll lock

format-prefix = "  "
format-underline = ${colors.sealine}
format-foreground = ${colors.sealine}
format-padding = 2

label-layout = %layout%
label-layout-foreground = ${colors.light}

;Battery Indicator
[module/battery]
type = internal/battery
battery = BAT0
full-at = 100
low-at = 10

format-charging = <animation-charging> <label-charging>
format-charging-padding = 2
format-charging-underline = ${colors.green}

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-padding = 2
format-discharging-underline = ${colors.green}

format-full = <ramp-capacity> <label-full>
format-full-padding = 2
format-full-underline = ${colors.green}

format-low = <animation-low> <label-low>
format-low-padding = 2
format-low-underline = ${colors.red}

label-charging = %percentage:2%%
label-discharging = %percentage:2%%
label-full = %percentage:2%%
label-low = %percentage:2%%

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-charging-foreground = ${colors.green}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-foreground  = ${colors.green}
ramp-capacity-font = 4

animation-low-0 = 
animation-low-1 = !
animation-low-framerate = 750
animation-low-foreground = ${colors.red}
animation-low-font = 4


[module/cpu]
type = internal/cpu
interval = 0.5
format = <label>
format-padding = 2
format-underline = ${colors.orange}

format-prefix = " "
format-prefix-foreground = ${colors.orange}

label = %percentage:02%%


[module/memory]
type = internal/memory
interval = 3
format = <label>
format-padding = 2
format-underline = ${colors.pink}

format-prefix = " "
format-prefix-foreground = ${colors.pink}

label = %used%


[module/filesystem]
type = internal/fs
interval = 3
mount-0 = /
format-mounted = <label-mounted>
format-mounted-padding = 2
format-mounted-underline = ${colors.red}

format-mounted-prefix = " "
format-mounted-prefix-foreground = ${colors.red}
format-mounted-prefix-font = 3

label-mounted = %used%


[module/tempscript]
type = custom/script
exec = printf "%s°C" $(sh ~/.config/polybar/tempscript.sh)
interval = 1

format-prefix = " "
format-prefix-font = 4
format-prefix-foreground = ${colors.purple}

format-padding = 2
format-underline = ${colors.purple}

;vim:ft=dosini
