[colors]
color-1 = #f0c000
color-2 = #1ca9d4
color-3 = #d33682
color-4 = #f28807
color-5 = #810d0c
color-6 = #0d80ac
color-7 = #589900
color-8 = #c86f8f
color-9 = #eecf71

light = #a8d8d8
dark = #0c0d11
gray = #788e95
dark-gray = #073642

translucent = #88073642
transparent = #00000000



[bar/bg-base]
enable-ipc = true

height = 50
width = 400

foreground = ${colors.light}
background = ${colors.transparent}

override-redirect = true
wm-restack = i3

font-0 = Fantasque Sans Mono:Bold:size=24


[bar/bg-clock]
inherit= bar/bg-base

radius = 100
height = 200
width = 550
offset-y = 990
offset-x = -100

background = ${colors.translucent}

font-0 = Fantasque Sans Mono:Bold:size=80;-8

modules-right = bg-clock placeholder placeholder

[bar/bg-date]
inherit = bar/bg-base

offset-y = 1110

foreground = ${colors.light}
background = ${colors.transparent}

modules-center = bg-date



[bar/base]
enable-ipc = true

bottom = false
radius = 16
height = 32
offset-y = 5

foreground = ${colors.dark}

override-redirect = true
wm-restack = i3

font-0 = Fantasque Sans Mono:Bold:size=12;4
font-1 = FantasqueSansMono Nerd Font Mono:Bold:size=24;5
font-2 = FantasqueSansMono Nerd Font Mono:Bold:size=19;4
font-3 = FantasqueSansMono Nerd Font Mono:Bold:size=16;4
font-4 = DejaVu Sans Code:Bold:size=40;5



# WS bars
[bar/ws-1]
inherit = bar/base
offset-x = 25
width = 32

background = ${colors.color-1}

modules-center = wsindicator-1

[bar/ws-2]
inherit = bar/base
offset-x = 65
width = 32

background = ${colors.color-2}

modules-center = wsindicator-2

[bar/ws-3]
inherit = bar/base
offset-x = 105
width = 32

background = ${colors.color-3}

modules-center = wsindicator-3

[bar/ws-4]
inherit = bar/base
offset-x = 145
width = 32

background = ${colors.color-4}

modules-center = wsindicator-4

[bar/ws-5]
inherit = bar/base
offset-x = 185
width = 32

background = ${colors.color-5}

modules-center = wsindicator-5

[bar/ws-6]
inherit = bar/base
offset-x = 225
width = 32

background = ${colors.color-6}

modules-center = wsindicator-6

[bar/ws-7]
inherit = bar/base
offset-x = 265
width = 32

background = ${colors.color-7}

modules-center = wsindicator-7

[bar/ws-8]
inherit = bar/base
offset-x = 305
width = 32

background = ${colors.color-8}

modules-center = wsindicator-8

[bar/ws-9]
inherit = bar/base
offset-x = 345
width = 32

background = ${colors.color-9}

modules-center = wsindicator-9

# Info bars
[bar/date]
inherit = bar/base
width = 110
offset-x = 579

background = ${colors.color-1}

modules-center = date

[bar/tempscript]
inherit = bar/base
width = 95
offset-x = 709

background = ${colors.color-2}

modules-center = tempscript

[bar/cpu]
inherit = bar/base
width = 85
offset-x = 824

background = ${colors.color-3}

modules-center = cpu

[bar/memory]
inherit = bar/base
width = 125
offset-x = 929

background = ${colors.color-4}

modules-center = memory

[bar/filesystem]
inherit = bar/base
width = 95 
offset-x = 1074

background = ${colors.color-5}

modules-center = filesystem

[bar/battery]
inherit = bar/base
width = 80
offset-x = 1189

background = ${colors.color-6}

modules-center = battery

[bar/layout]
inherit = bar/base
width = 82
offset-x = 1289

background = ${colors.color-7}

modules-center = layout

[bar/sound]
inherit = bar/base
width = 85
offset-x = 1391

background = ${colors.color-8}

modules-center = sound

[bar/brightness]
inherit = bar/base
width = 85
offset-x = 1496

click-left = ~/.config/polybar/slider.py 10 "light -T 1.1" "light -T 0.909090909"

background = ${colors.color-9}

modules-center = brightness

[bar/tray]
inherit = bar/base
width = 352
offset-x = 1783

background = ${colors.gray}

tray-position = center
modules-left = placeholder



# Bars in tablet mode
[bar/base-tablet]
enable-ipc = true

bottom = false
offset-y = 10
radius = 28
height = 54
width = 54

foreground = ${colors.dark}

line-size = 5
separator = " "

override-redirect = true
wm-restack = i3

font-0 = Fantasque Sans Mono:Bold:size=18;3
font-1 = FantasqueSansMono Nerd Font Mono:Bold:size=36;7
font-2 = FantasqueSansMono Nerd Font Mono:Bold:size=30;5
font-3 = FantasqueSansMono Nerd Font Mono:Bold:size=24;3
font-4 = DejaVu Sans Code:Bold:size=67;7
font-5 = DejaVu Sans Code:Bold:size=67;12

# WS bars
[bar/ws-1-tablet]
inherit = bar/base-tablet
offset-x = 25

background = ${colors.color-1}

modules-center = wsindicator-1

[bar/ws-2-tablet]
inherit = bar/base-tablet
offset-x = 95

background = ${colors.color-2}

modules-center = wsindicator-2

[bar/ws-3-tablet]
inherit = bar/base-tablet
offset-x = 165

background = ${colors.color-3}

modules-center = wsindicator-3

[bar/ws-4-tablet]
inherit = bar/base-tablet
offset-x = 235

background = ${colors.color-4}

modules-center = wsindicator-4

[bar/ws-5-tablet]
inherit = bar/base-tablet
offset-x = 305

background = ${colors.color-5}

modules-center = wsindicator-5

[bar/ws-6-tablet]
inherit = bar/base-tablet
offset-x = 375

background = ${colors.color-6}

modules-center = wsindicator-6

[bar/ws-7-tablet]
inherit = bar/base-tablet
offset-x = 445

background = ${colors.color-7}

modules-center = wsindicator-7

[bar/ws-8-tablet]
inherit = bar/base-tablet
offset-x = 515

background = ${colors.color-8}

modules-center = wsindicator-8

[bar/ws-9-tablet]
inherit = bar/base-tablet
offset-x = 585

background = ${colors.color-9}

modules-center = wsindicator-9

;LANDSCAPE
[bar/date-landscape]
inherit = bar/base-tablet

offset-x = 792
width = 150

background = ${colors.color-1}

modules-center = date

[bar/battery-landscape]
inherit = bar/base-tablet

offset-x = 962
width = 115

background = ${colors.color-6}

modules-center = battery

[bar/sound-landscape]
inherit = bar/base-tablet

offset-x = 1097
width = 125

background = ${colors.color-8}

modules-center = sound

[bar/brightness-landscape]
inherit = bar/base-tablet

offset-x = 1242
width = 125

click-left = ~/.config/polybar/slider.py 10 "light -T 1.1" "light -T 0.909090909"

background = ${colors.color-9}

modules-center = brightness

[bar/X-landscape]
inherit = bar/base-tablet
offset-x = 2081

background = ${colors.color-5}

modules-center = X

[bar/tray-landscape]
inherit = bar/base-tablet

offset-x = 1521
width = 544

background = ${colors.gray}

modules-left = placeholder

tray-position = center

;PORTRAIT
[bar/date-portrait]
inherit = bar/date-landscape

offset-x = 25
offset-y = 2096

[bar/battery-portrait]
inherit = bar/battery-landscape

offset-x = 195
offset-y = 2096

[bar/sound-portrait]
inherit = bar/sound-landscape

offset-x = 330
offset-y = 2096

[bar/brightness-portrait]
inherit = bar/brightness-landscape

click-left = ~/.config/polybar/slider.py 10 "light -T 1.1" "light -T 0.909090909"

offset-x = 475
offset-y = 2096

[bar/X-portrait]
inherit = bar/X-landscape
offset-x = 1361

[bar/tray-portrait]
inherit = bar/tray-landscape

offset-x = 840
offset-y = 2096
width = 575

[bar/bg-clock-portrait]
inherit = bar/bg-clock

offset-y = 1710

[bar/bg-date-portrait]
inerit = bar/bg-date

offset-y = 1830




; MODULES

;placeholder
[module/placeholder]
type = custom/text
content = " "


[module/X]
type = custom/text
content = ⊗
click-left = i3-msg kill
content-font = 6


;Background clock
[module/bg-clock]
type = internal/date
time = %H:%M
date = %H:%M

;Background date
[module/bg-date]
type = internal/date
date = %Y. %B %e.


;Date 1
[module/date]
type = internal/date

time = %H:%M
time-alt =
date =
date-alt = %d/%m

format-prefix = "  "

label = %date%%time%

;CPU temerature 2
[module/tempscript]
type = custom/script
exec = ~/.config/polybar/tempscript.sh
interval = 1

format-prefix = " "
format-prefix-font = 4

format-padding = 2

label = %output%°C

;CPU usage 3
[module/cpu]
type = internal/cpu
interval = 0.5
format = <label>
format-padding = 2

format-prefix = " "

label = %percentage:2%%

;Memory usage 4
[module/memory]
type = internal/memory
interval = 3
format = <label>
format-padding = 2

format-prefix = " "

label = %used%

;Filesystem usage 5
[module/filesystem]
type = internal/fs
interval = 3
mount-0 = /
format-mounted = <label-mounted>
format-mounted-padding = 2

format-mounted-prefix = " "
format-mounted-prefix-font = 3

label-mounted = %used%

;Battery Indicator 6
[module/battery]
type = internal/battery
battery = BAT0
full-at = 100
low-at = 10

format-charging = <animation-charging> <label-charging>
format-charging-padding = 2

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-padding = 2

format-full = <ramp-capacity> <label-full>
format-full-padding = 2

format-low = <animation-low> <label-low>
format-low-padding = 2

label-charging = %percentage:2%%
label-discharging = %percentage:2%%
label-full = %percentage:2%%
label-low = %percentage:2%%

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-font = 4

animation-low-0 = 
animation-low-1 = !
animation-low-framerate = 750
animation-low-foreground = ${colors.color-5}
animation-low-font = 4

;Keyboard Layout 7
[module/layout]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = caps lock
blacklist-2 = scroll lock

format-prefix = "  "
format-padding = 2

label-layout = %layout%

;Sound 8
[module/sound]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-volume-padding = 2

label-volume = %percentage:2%%

label-muted =  %percentage:2%%
label-muted-padding = 2

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 


;Brightness 9
[module/brightness]
type = internal/backlight
card = intel_backlight
format = <label>
format-padding = 2
format-prefix = " "

click-left = ~/.config/polybar/slider.py 10 "light -T 1.1" "light -T 0.909090909"

label = %percentage:2%%


[module/wsindicator-base]
type = custom/ipc

format-font = 5

hook-0 = echo ◌
hook-1 = echo ◉
hook-2 = echo ◍
hook-3 = echo ○

[module/wsindicator-1]
inherit = module/wsindicator-base
click-left = i3-msg workspace 1;~/.config/polybar/wsindicator-update
[module/wsindicator-2]
inherit = module/wsindicator-base
click-left = i3-msg workspace 2;~/.config/polybar/wsindicator-update
[module/wsindicator-3]
inherit = module/wsindicator-base
click-left = i3-msg workspace 3;~/.config/polybar/wsindicator-update
[module/wsindicator-4]
inherit = module/wsindicator-base
click-left = i3-msg workspace 4;~/.config/polybar/wsindicator-update
[module/wsindicator-5]
inherit = module/wsindicator-base
click-left = i3-msg workspace 5;~/.config/polybar/wsindicator-update
[module/wsindicator-6]
inherit = module/wsindicator-base
click-left = i3-msg workspace 6;~/.config/polybar/wsindicator-update
[module/wsindicator-7]
inherit = module/wsindicator-base
click-left = i3-msg workspace 7;~/.config/polybar/wsindicator-update
[module/wsindicator-8]
inherit = module/wsindicator-base
click-left = i3-msg workspace 8;~/.config/polybar/wsindicator-update
[module/wsindicator-9]
inherit = module/wsindicator-base
click-left = i3-msg workspace 9;~/.config/polybar/wsindicator-update

;vim:ft=dosini
