#!/bin/bash

cd "$(dirname "$0")"

case "$1" in
    "")
        if [[ "$(./group-msg tray 2>&1 > /dev/null)" == "polybar-msg"* ]]; then
            echo "down"
        elif ls ./active-mode &>/dev/null; then
            echo "laptop"
        else
            cat active-mode
        fi
        exit
        ;;
    "lock")
        touch lock
        ./group-msg lock hook 1
        exit
        ;;
    "unlock")
        rm -f lock
        ./group-msg lock hook 0
        exit
        ;;
    "locked")
        if ls lock &>/dev/null; then
            exit
        fi
        exit 1
        ;;
    "toggle")
        if [[ "$2" = "lock" ]]; then
            if ./mode locked; then
                ./mode unlock
            else
                ./mode lock
            fi
            exit
        fi
        ;;
esac

if [[ "$1" = "force" ]]; then
    shift 1
else
    if ./mode locked; then
        exit 1
    fi
fi

case "$1" in
    "laptop")
        ./group-msg tray quit
        ./group-msg wss-tablet hide
        ./group-msg portrait hide
        ./group-msg landscape hide
        i3-msg gaps top all set 17
        i3-msg gaps bottom all set 0
        echo laptop > ./active-mode
        ./wsupdater.py single-shot
        ./group-msg wss show
        ./group-msg sysinfo show
        polybar -q tray &
        feh --bg-fill ~/.config/i3/wallpaper
        ./group 1 tray
        ;;
    "tablet")
        ./group-msg wss hide
        ./group-msg sysinfo hide
        i3-msg gaps top all set 49
        echo tablet > ./active-mode
        ./wsupdater.py single-shot
        ./group-msg wss-tablet show
        ;;
    "portrait")
        ./group-msg tray quit
        ./group-msg landscape hide
        i3-msg gaps bottom all set 49
        ./group-msg portrait show
        polybar -q tray-portrait &
        feh --bg-fill ~/.config/i3/wallpaper
        ./group 1 tray
        echo portrait > ./active-mode
        ;;
    "landscape")
        ./group-msg tray quit
        ./group-msg portrait hide
        i3-msg gaps bottom all set 0
        ./group-msg landscape show
        polybar -q tray-landscape &
        feh --bg-fill ~/.config/i3/wallpaper
        ./group 1 tray
        echo landscape > ./active-mode
        ;;
    *)
        echo "Usage: $0 [[force] laptop|tablet|portrait|landscape | lock|unlock|locked|toggle lock]"
        ;;
esac
